<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestSAPR.Application\TestSAPR.Application.csproj" />
    <ProjectReference Include="..\TestSAPR.Infrastructure\TestSAPR.Infrastructure.csproj" />
  </ItemGroup>

</Project>
